### ISSUE TITLE
Last opp bilder

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMbilder#13]
Integrer opplasting av bilder i UKMbilder

Det skal være mulig å laste opp ett eller flere bilder via drag-n-drop på UKMbilder. Bildene må lastes opp i riktig rekkefølge, slik at de blir lagt til i databasen i samme rekkefølge som de er lastet opp. 

Tidligere controller for uploading:
https://github.com/UKMNorge/UKMbilder/blob/master/ajax_uploaded_image.inc.php

I tillegg til eksisterende funksjonalitet, må bildets opprinnelige filnavn lagres i databasetabellen

Viktig:
- [x] Max concurrent fileupload == 1
- [x] Filnavn på opplastet fil må lagres (legg til ekstra felt her; `uploaded_filename`)
https://github.com/UKMNorge/UKMbilder/blob/master/ajax_uploaded_image.inc.php#L31
- [x] `UKMbilder_syncfolder()` må byttes ut med konstanten `UKM_BILDER_SYNC_FOLDER` i `UKMconfig.inc.php` (denne er ikke definert per i dag). Verdi i ukm.dev: `/var/www/sync/` og i ukm.no:`/home/ukmno/private_sync/`

**Comment by Jimtrim** [comment]
Upload fungerer, og Process.js får JSON-data fra upload.js, klar for videre behandling
