### ISSUE TITLE
Konverter bilder

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMbilder#14]
Når et bilde er lastet opp, må det legges til i konverteringskø, som konverteres fortløpende.

Ved page-load må listen worklist fylles ut med ikke-komprimerte bilder, slik at konverteringen stopper opp igjen.
Konverterings-"appen" må også lytte til uploader-"appen", og ta inn alle bilder som er ferdig opplastet.

Tidligere kontroller for komprimering:
https://github.com/UKMNorge/UKMbilder/blob/master/ajax_compress.inc.php

Bilder som ikke er komprimert finnes ved følgende spørring:
https://github.com/UKMNorge/UKMbilder/blob/master/ajax_compress.inc.php#L34-L39

**Comment by Jimtrim** [comment]
Utført, og commit'a til redesign-branch
