### ISSUE TITLE
Tagg bilder

### ISSUE THREAD

**Issue by mariusmandal** [UKMNorge/UKMbilder#16]
Det må være mulig å merke alle bilder med innslag.

Bildet som skal vises, må også ha følgende info:
- Opprinnelig filnavn
- Tidspunkt for foto

Selve taggingen må ha:
- [x] Select-liste med alle brukere på bloggen (fotograf)
- [x] Select-liste med alle hendelser på arrangementet `$arrangement->getProgram()->getAbsoluteAll()`

On change på hendelser-listen, må rekkefølgen på alle innslag i hendelsen listes ut nedenfor selectlisten
```twig 
{% for( innslag in  arrangement.getProgram().getHendelse($hendelsens_ID).getInnslag().getAll() ) %}
  <input type="radio">{{ innslag.getNavn() }}</input>
{% endfor %}
```

**Comment by Jimtrim** [comment]
Funksjonalitet for å tagge bilder og navigere aktiv tag-kø er oppe og går
