### ISSUE TITLE
Bruk TwigJS eller noe annet for å gjenbruke HTML-elementer

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMbilder#28]
I stedet for som nå at f.eks konverterer-køa ved innlast kommer fra home.html.twig, og ved opplasting kommer fra en appenda html-string i JS.

**Comment by mariusmandal** [comment]
Det er bare å opprette mappa "js" i twig, så håndterer den resten selv @AsgeirSH 
For å bruke den:
```
    jQuery('#target').html(twigJS_`filnavn`.render(result)).slideDown();
```
hvor `filnavn` gjennomgår følgende str_replace: 
```php
array('.html.twig','_','.'), array('', '','_')
```
