### ISSUE TITLE
Lagrer du siste bildet i taggekøen blir du stående på samme bildet uten noen info ved suksess

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMbilder#29]
Related #27

**Comment by AsgeirSH** [comment]
@mariusmandal Tror ikke jeg gjør noe med denne umiddelbart - må se over hvordan vi refresher taggekø underveis i tagging for å få en bra brukeropplevelse om vi skal endre denne tror jeg.

**Comment by mariusmandal** [comment]
Ved lagre-success, og fokus på siste bilde i køen, la brukeren få opp en alert som det står `Bra jobba! Siste bilde i køen er lagret.`-ish
