### ISSUE TITLE
Tillat sletting av ikke-taggede og ikke-konverterte bilder

### ISSUE THREAD

**Issue by AsgeirSH** [UKMNorge/UKMbilder#6]
Hendig for eksempel om man laster opp ett eller flere bilder to ganger, konverteringen har krasja, eller man har mista oversikten på hvilket bilde som er hva.

Det vil også gjøre det enklere for nye veiledere å teste ut systemet i forkant uten å måtte bruke reelle data, som kan gi mindre support på bilder-modulen.

**Comment by mariusmandal** [comment]
Er det mulig å kjøre en hash-sjekk for å se om bildet allerede ligger i kø?

**Comment by mariusmandal** [comment]
Løses av #16
